"""empty message

Revision ID: 0c1b7f7bdbae
Revises: da2d13de37be
Create Date: 2021-06-23 23:01:10.807854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1b7f7bdbae'
down_revision = 'da2d13de37be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_text_key', 'todo', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('todo_text_key', 'todo', ['text'])
    # ### end Alembic commands ###
