"""empty message

Revision ID: 4e10de941629
Revises: a8dc39d5f30c
Create Date: 2021-06-23 16:06:27.560833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e10de941629'
down_revision = 'a8dc39d5f30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_description_key', 'todo', type_='unique')
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint('todo_description_key', 'todo', ['description'])
    # ### end Alembic commands ###
