"""empty message

Revision ID: a8dc39d5f30c
Revises: a46843fc6032
Create Date: 2021-06-21 23:22:04.544704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8dc39d5f30c'
down_revision = 'a46843fc6032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('due_date', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'todo', ['due_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='unique')
    op.drop_column('todo', 'due_date')
    # ### end Alembic commands ###
