"""empty message

Revision ID: da2d13de37be
Revises: ddf29ac65170
Create Date: 2021-06-23 22:59:08.091919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2d13de37be'
down_revision = 'ddf29ac65170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_title_key', 'todo', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('todo_title_key', 'todo', ['title'])
    # ### end Alembic commands ###
