"""empty message

Revision ID: ddc8799a6ec0
Revises: 0c1b7f7bdbae
Create Date: 2021-06-23 23:01:36.902680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc8799a6ec0'
down_revision = '0c1b7f7bdbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_created_at_key', 'todo', type_='unique')
    op.drop_constraint('todo_due_date_key', 'todo', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('todo_due_date_key', 'todo', ['due_date'])
    op.create_unique_constraint('todo_created_at_key', 'todo', ['created_at'])
    # ### end Alembic commands ###
