"""empty message

Revision ID: ddf29ac65170
Revises: 629295e91607
Create Date: 2021-06-23 16:09:00.895420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf29ac65170'
down_revision = '629295e91607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_user_id_key', 'todo', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('todo_user_id_key', 'todo', ['user_id'])
    # ### end Alembic commands ###
